steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'gcr.io/able-math-347003/myfirstproject', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/able-math-347003/myfirstproject']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myfirstproject', '--image', 'gcr.io/able-math-347003/myfirstproject', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/able-math-347003/myfirstproject